# add this file to the docker compose execution when developing Squest
services:

  db:
    ports:
      - "5432:5432"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  redis-cache:
    ports:
      - "6379:6379"
